# model
model:
  name: "Qwen/Qwen2.5-Coder-3B"
  type: "qwen"
  temperature: 0.7
  top_p: 0.9
  max_length: 2048
  tokenizer_kwargs:
    trust_remote_code: true
  model_kwargs:
    trust_remote_code: true
    torch_dtype: "bfloat16"

# dataset
dataset:
  name: "OpenMLRL/MBPP"
  type: "mbpp"
  train_split: "test[15:65]"
  eval_split: "test[:15]"

# output
output:
  base_dir: "output"
  save_final_model: false
  verbose: false

# external
external:
  mode: "level_feedback"
  sandbox_slice: 1

# grpo
grpo:
  num_turns: 2
  num_train_epochs: 8
  per_device_train_batch_size: 1
  learning_rate: 3.0e-5
  logging_steps: 5
  eval_interval: 20
  eval_num_samples: 15
  num_generations: 4
  max_new_tokens: 256
  joint_mode: aligned
  temperature: 0.8
  top_p: 0.95
  top_k: null
  discount: 0.9
  termination_threshold: -0.1
  reward_shift: -2.1

# wandb
wandb:
  project: "comlrl"
  entity: "OpenMLRL"
  name: "grpo_mbpp"
  dir: "output"
  tags: ["grpo", "mbpp"]
